# Generated by Django 2.1.7 on 2020-01-17 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200117_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 17, 13, 59, 8, 301680)),
        ),
    ]
